[package]
name = "nico_bot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
block-on = "0.3.0"
ollama-rs = "0.1.7"
async-std = { version = "1", features = ["attributes", "tokio1"] }
